name: Shell scripts validation

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Validate shell scripts
        run: |
          for f in `find . -name "*sh"`; do
            shellcheck $f
          done